export const navItems = [
  { label: 'Dashboard', path: '/' },
  { label: 'Projects', path: '/projects' },
  { label: 'Backlog', path: '/backlog' },
  { label: 'Sprint', path: '/sprint' },
  { label: 'Analytics', path: '/analytics' },
]

export const usersSeed = [
  { id: 'usr-1', name: 'Avery Stone', email: 'avery@beacon.pm', role: 'MANAGER', capacityPerSprint: 14 },
  { id: 'usr-2', name: 'Nina Patel', email: 'nina@beacon.pm', role: 'DEVELOPER', capacityPerSprint: 10 },
  { id: 'usr-3', name: 'Leo Martinez', email: 'leo@beacon.pm', role: 'DEVELOPER', capacityPerSprint: 8 },
  { id: 'usr-4', name: 'Mia Chen', email: 'mia@beacon.pm', role: 'DEVELOPER', capacityPerSprint: 8 },
  { id: 'usr-5', name: 'Jordan Kim', email: 'jordan@beacon.pm', role: 'ADMIN', capacityPerSprint: 12 },
]

export const projectsSeed = [
  {
    id: 'proj-1',
    name: 'Beacon Platform Refresh',
    description: 'Refreshing the core experience for project tracking, analytics, and release coordination.',
    createdBy: 'usr-1',
    teamMembers: ['usr-1', 'usr-2', 'usr-3', 'usr-4'],
    status: 'ACTIVE',
    summary: 'Core modernization work for the Beacon workspace.',
    deadline: '2026-04-18',
  },
  {
    id: 'proj-2',
    name: 'Mobile Notifications Rollout',
    description: 'Shipping preferences, digests, and notification targeting for release teams.',
    createdBy: 'usr-5',
    teamMembers: ['usr-2', 'usr-4', 'usr-5'],
    status: 'PLANNED',
    summary: 'Push notification rollout across mobile squads.',
    deadline: '2026-05-06',
  },
  {
    id: 'proj-3',
    name: 'Analytics Workspace',
    description: 'Creating a shared dashboard for velocity, sprint health, and workload insights.',
    createdBy: 'usr-3',
    teamMembers: ['usr-1', 'usr-3', 'usr-5'],
    status: 'AT_RISK',
    summary: 'Analytics foundation for Beacon reporting.',
    deadline: '2026-04-29',
  },
]

export const sprintsSeed = [
  {
    id: 'spr-12',
    projectId: 'proj-1',
    name: 'Sprint 12',
    startDate: '2026-03-25',
    endDate: '2026-04-05',
    status: 'ACTIVE',
    committedStoryPoints: 40,
    completedStoryPoints: 28,
  },
  {
    id: 'spr-13',
    projectId: 'proj-2',
    name: 'Sprint 13',
    startDate: '2026-04-08',
    endDate: '2026-04-19',
    status: 'PLANNED',
    committedStoryPoints: 32,
    completedStoryPoints: 0,
  },
  {
    id: 'spr-11',
    projectId: 'proj-3',
    name: 'Sprint 11',
    startDate: '2026-03-10',
    endDate: '2026-03-22',
    status: 'COMPLETED',
    committedStoryPoints: 26,
    completedStoryPoints: 20,
  },
]

export const tasksSeed = [
  {
    id: 'TSK-101',
    projectId: 'proj-1',
    sprintId: 'spr-12',
    title: 'Refine role-based permissions matrix',
    description: 'Finalize permission combinations for manager, admin, and developer roles.',
    assignedTo: 'usr-1',
    priority: 'HIGH',
    storyPoints: 5,
    status: 'IN_PROGRESS',
    risk: 0.2,
    businessValue: 9,
    riskFactor: 4,
    urgency: 8,
  },
  {
    id: 'TSK-102',
    projectId: 'proj-1',
    sprintId: 'spr-12',
    title: 'Wire dashboard metrics cards',
    description: 'Build metric surfaces for velocity, sprint health, and task throughput.',
    assignedTo: 'usr-3',
    priority: 'HIGH',
    storyPoints: 8,
    status: 'DONE',
    risk: 0.1,
    businessValue: 8,
    riskFactor: 3,
    urgency: 7,
  },
  {
    id: 'TSK-103',
    projectId: 'proj-1',
    sprintId: 'spr-12',
    title: 'Investigate flaky sprint burndown widget',
    description: 'Find the stale render issue in the analytics refresh cycle.',
    assignedTo: 'usr-4',
    priority: 'HIGH',
    storyPoints: 3,
    status: 'BLOCKED',
    risk: 0.7,
    businessValue: 7,
    riskFactor: 9,
    urgency: 8,
  },
  {
    id: 'TSK-104',
    projectId: 'proj-2',
    sprintId: 'spr-13',
    title: 'Map notification preference API contract',
    description: 'Prepare request and response shapes for settings controls.',
    assignedTo: 'usr-2',
    priority: 'MEDIUM',
    storyPoints: 5,
    status: 'TODO',
    risk: 0.2,
    businessValue: 8,
    riskFactor: 4,
    urgency: 6,
  },
  {
    id: 'TSK-105',
    projectId: 'proj-2',
    sprintId: null,
    title: 'Draft onboarding checklist for new project leads',
    description: 'Create the first backlog item for launch readiness support.',
    assignedTo: 'usr-5',
    priority: 'MEDIUM',
    storyPoints: 2,
    status: 'TODO',
    risk: 0.1,
    businessValue: 5,
    riskFactor: 2,
    urgency: 4,
  },
  {
    id: 'TSK-106',
    projectId: 'proj-3',
    sprintId: 'spr-11',
    title: 'Add release notes card to dashboard summary',
    description: 'Expose release readiness notes inside the executive view.',
    assignedTo: 'usr-3',
    priority: 'LOW',
    storyPoints: 3,
    status: 'DONE',
    risk: 0.1,
    businessValue: 4,
    riskFactor: 2,
    urgency: 3,
  },
  {
    id: 'TSK-107',
    projectId: 'proj-3',
    sprintId: 'spr-11',
    title: 'Calculate sprint health score service',
    description: 'Implement the weighted formula described in the analytics doc.',
    assignedTo: 'usr-1',
    priority: 'HIGH',
    storyPoints: 8,
    status: 'DONE',
    risk: 0.2,
    businessValue: 10,
    riskFactor: 5,
    urgency: 8,
  },
  {
    id: 'TSK-108',
    projectId: 'proj-1',
    sprintId: 'spr-12',
    title: 'Validate new login experience copy',
    description: 'Polish messaging for demo access and mock authentication.',
    assignedTo: 'usr-2',
    priority: 'LOW',
    storyPoints: 2,
    status: 'IN_PROGRESS',
    risk: 0.15,
    businessValue: 3,
    riskFactor: 1,
    urgency: 2,
  },
]
